name: luxai_s2_jax
channels:
  - conda-forge
dependencies:
  - python=3.8
  - numpy
  - matplotlib
  - scipy
  - pip
  - cython
  - tqdm
  - yaml
  - gym=0.21

  - pip:
    - pettingzoo
    - termcolor
    - pygame
    - vec_noise
    - omegaconf
    - stable_baselines3
    - luxai_s2
    - juxai-s2

